version: "3.8"
name: my-project-prod
services:
  server:
    container_name: my-project-prod-server
    image: akbarnafisa/my-project-prod-server:${PROD_IMAGE_TAG}
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/server/dockerfile.prod
    env_file:
      - stack.env
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - postgres
    command: yarn workspace server start
    volumes:
      - init-db-data:/main/apps/server/init-db
    networks:
      - nginx.docker
      - my-project-server-prod-network
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: my-project-prod-postgres
    env_file:
      - stack.env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-prod:/var/lib/postgresql/data
      - init-db-data:/docker-entrypoint-initdb.d
    networks:
      - my-project-server-prod-network
volumes:
  db-prod:
    driver: local
  init-db-data:
    driver: local

networks:
  nginx.docker:
    name: nginx.docker
    external: true
  my-project-server-prod-network: