FROM node:18-alpine

WORKDIR /main

COPY packages/libs/package.json packages/libs/package.json
COPY packages/validation/package.json  packages/validation/package.json 
COPY apps/server/package.json apps/server/package.json 

COPY package.json .
COPY yarn.lock .

RUN yarn install --pure-lockfile --cache-folder ./yarncache; rm -rf ./yarncache; 

COPY packages/libs packages/libs
COPY packages/validation packages/validation
COPY apps/server apps/server